#!/bin/bash

thisdir=$(dirname "${BASH_SOURCE[0]}")
export BUILD_PACKAGE="loopback-oracle"

ORA_PACKAGES_DIR=$(cd -P -- "$thisdir/../deps/oracle" && pwd -P)

BUILD_ARCH="Unknown"
BUILD_PLATFORM="Unknown"

#
#  Print error message and exit with the specified code.
#
#  Examples:
#    die 'This sucks!' 101
#
function die() {
  [ -n "$1" ] && echo "$1"
  exit ${2:-"-1"}

}  #  End of function  die.


#
#  Prints the specified message - formatted.
#
#  Examples:
#    print_message "Initializing ..."
#
function print_message() {
  # echo "$@" | sed "s/^/\t/"
  if [ -n "$@" ]; then
    echo "  $@"
  else
    echo ""
  fi

  return 0

}  #  End of function  print_message.


#
#  Print env variables for package, version, platform, os and architecture.
#
#  Examples:
#    print_env_variables
#
function print_env_variables() {
   print_message "-  Package = $BUILD_PACKAGE"
   print_message "-  Version = $BUILD_VERSION"
   print_message "- Platform = $BUILD_PLATFORM"
   print_message "-     Arch = $BUILD_ARCH"
   print_message "-      ABI = $BUILD_NODE_MODULE_VERSION"
   print_message "-   Module = $NODE_ORACLE_MODULE"

}  #  End of function  print_env_variables.


#
#
#  Detects the platform we are running the build on.
#
#  Examples:
#    detect_platform
#
function detect_platform() {
  info=$(node ../lib/detect.js)

  export BUILD_PLATFORM=$(echo $info|cut -f1 -d ' ')
  export BUILD_ARCH=$(echo $info|cut -f2 -d ' ')
  export BUILD_VERSION=$(echo $info|cut -f3 -d ' ')
  export BUILD_DRIVER_VERSION=$(echo $info|cut -f4 -d ' ')
  export BUILD_DRIVER_MODULE=$(echo $info|cut -f5 -d ' ')
  export BUILD_NODE_MODULE_VERSION=$(echo $info|cut -f6 -d ' ')

  if [ "$BUILD_NODE_MODULE_VERSION" == "undefined" ]; then
    export BUILD_TAR_BALL=${BUILD_PACKAGE}-${BUILD_PLATFORM}-${BUILD_ARCH}-${BUILD_VERSION}.tar
  else
    export BUILD_TAR_BALL=${BUILD_PACKAGE}-${BUILD_PLATFORM}-${BUILD_ARCH}-abi${BUILD_NODE_MODULE_VERSION}-${BUILD_VERSION}.tar
  fi

  if [ "$BUILD_DRIVER_MODULE" == "undefined" ]; then
    if which -s git; then
      export NODE_ORACLE_MODULE="strongloop/strong-oracle#$BUILD_DRIVER_VERSION"
    else
      export NODE_ORACLE_MODULE="http://github.com/strongloop/strong-oracle/tarball/$BUILD_DRIVER_VERSION"
    fi
  else
    export NODE_ORACLE_MODULE=$BUILD_DRIVER_MODULE
  fi

  if [ -z $1 ]; then
    print_env_variables
  fi
  return 0

}  #  End of function  detect_platform.


